### ISSUE TITLE
Clarify relationship to Nerves.Networking?

### ISSUE THREAD

**Issue by artob** [nerves-project/nerves_network_interface#1]
Perhaps the README might include a paragraph about the relationship between nerves_network_interface and [nerves_networking](https://github.com/nerves-project/nerves_networking)? There seems to be some overlap in functionality/scope, but it isn't abundantly clear right now how (if at all) these projects relate to one another.

**Comment by fhunleth** [comment]
Thanks for opening the issue. I should write something up. Basically, nerves_network_interface handles low level access to Linux network interfaces. The nerves_interim_wifi project uses it to trigger when wifi adapters are added to the system and also to configure the IP address, etc. on the Linux network interface. The nerves_networking project calls the `ip` program to set up the low level configuration, but that's mainly because nerves_networking was written before nerves_network_interface existed. 

@ghitchens - I assume that you're still a ways off from updating nerves_networking. If you have something or plans changed, let me know.

**Comment by GregMefford** [comment]
Resolved for now by #2. More improvements to come as we re-factor the wired and wireless networking code.
