### ISSUE TITLE
Compilation Error on RPi0

### ISSUE THREAD

**Issue by idahogray** [nerves-project/nerves_network_interface#16]
Hello,

I am just getting started with nerves and was able to get the blinky example to work. I moved on to the hello_network example and ran into a compilation error on this dependency. I am probably doing something wrong and suggestions would be helpful. I have attached the output of the mix firmware command.

[firmware.txt](https://github.com/nerves-project/nerves_network_interface/files/1502244/firmware.txt)

**Comment by fhunleth** [comment]
I'm not currently seeing it, but this is a recent change that might be related: https://github.com/nerves-project/nerves_network_interface/commit/ee99d499866fa6a51f8d56f49104d097a0b8586e. If that's the case, then overriding the `nerves_network_interface` version to 0.4.2 instead of using 0.4.3 would fix it.

**Comment by electricshaman** [comment]
Placing the following line in the `mix.exs` deps for `hello_network` does resolve the issue for me:

```elixir
{:nerves_network_interface, "== 0.4.2", override: true}
```

**Comment by idahogray** [comment]
Thanks, pinning the dependency to 0.4.2 allowed me to build the firmware. I really appreciate you both responding. Have a holiday season!

Is there anything I can do to help find the problem with 0.4.3?

**Comment by fhunleth** [comment]
I finally reproduced the issue. It turns out that it worked for me due to my Linux laptop having a header file, libmnl.h, in the default include paths. That file isn't normally available. The change to to improve a flag detection test added that include file but not the include paths to support it. That's fixed now.

I made a 0.4.4 release. If you update your deps, you should be able to compile with the latest and greatest release again.

**Comment by idahogray** [comment]
I updated to 0.4.4 and confirm that it compiles. Thanks again for the help.
